language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm
branches:
  only:
    - develop
    - master
before_script:
  - composer self-update
  - composer -n --no-ansi install --dev --prefer-source
script:
  - ./bin/phpunit --verbose

