language: php
php:
  - 5.3
  - 5.4
  - 5.5
branches:
  only:
    - develop
    - master
before_script:
  - composer self-update
  - composer -n --no-ansi --dev install
script:
  - ./bin/phpunit --verbose

